// Generated by https://quicktype.io
export interface MoviesResponse {
    dates?: Dates;
    page: number;
    results: MovieResponse[];
    total_pages: number;
    total_results: number;
}

export interface Dates {
    maximum: string;
    minimum: string;
}

export interface MovieResponse {
    adult: boolean;
    backdrop_path: string;
    genre_ids: number[];
    id: number;
    original_title: string;
    overview: string;
    popularity: number;
    poster_path: string;
    release_date: string;
    title: string;
    video: boolean;
    vote_average: number;
    vote_count: number;
}

export enum OriginalLanguage {
    De = "de",
    En = "en",
    Es = "es",
}

// Generated by https://quicktype.io
export interface MovieDetailResponse {
    adult: boolean;
    backdrop_path: string;
    belongs_to_collection: null;
    budget: number;
    genres: GenreResponse[];
    homepage: string;
    id: number;
    imdb_id: string;
    original_language: string;
    original_title: string;
    overview: string;
    popularity: number;
    poster_path: string;
    production_companies: ProductionCompany[];
    production_countries: ProductionCountry[];
    release_date: string;
    revenue: number;
    runtime: number;
    spoken_languages: SpokenLanguage[];
    status: string;
    tagline: string;
    title: string;
    video: boolean;
    vote_average: number;
    vote_count: number;
    credits?: CreditsResponse;
    videos?: VideoResponse;
    reviews?: ReviewResponse
}

export interface GenreResponse {
    id: number;
    name: string;
}

export interface ProductionCompany {
    id: number;
    logo_path: null;
    name: string;
    origin_country: string;
}

export interface ProductionCountry {
    iso_3166_1: string;
    name: string;
}

export interface SpokenLanguage {
    english_name: string;
    iso_639_1: string;
    name: string;
}

// Generated by https://quicktype.io
export interface CreditsResponse {
    id?: number;
    cast: Cast[];
    crew: Cast[];
}

export interface Cast {
    adult: boolean;
    gender: number;
    id: number;
    known_for_department: string;
    name: string;
    original_name: string;
    popularity: number;
    profile_path: null | string;
    cast_id?: number;
    character?: string;
    credit_id: string;
    order?: number;
    department?: string;
    job?: string;
}

// Generated by https://quicktype.io
export interface VideoResponse {
    id?: number;
    results: VideoDetail[];
}

export interface VideoDetail {
    iso_639_1: string;
    iso_3166_1: string;
    name: string;
    key: string;
    site: string;
    size: number;
    type: string;
    official: boolean;
    published_at: string;
    id: string;
}

// Generated by https://quicktype.io
export interface ReviewResponse {
    id?: number;
    page: number;
    results: Review[];
    total_pages: number;
    total_results: number;
}

export interface Review {
    author: string;
    author_details: AuthorDetails;
    content: string;
    created_at: string;
    id: string;
    updated_at: string;
    url: string;
}

export interface AuthorDetails {
    name: string;
    username: string;
    avatar_path: string;
    rating: number;
}

// Generated by https://quicktype.io
export interface GenresResponse {
    genres: GenreResponse[];
}

export interface GenreResponse {
    id: number;
    name: string;
}


