export const Images = {
  gradient: require('./gradient.png'),
  user: require('./user.jpg'),
  genreAction: require('./action.jpg'),
  genreAdventure: require('./adventure.jpg'),
  genreAnimation: require('./animation.jpg'),
  genreComedy: require('./comedy.jpg'),
  genreCrime: require('./crime.jpg'),
  pin: require('./pin.png'),
  userPin: require('./user_pin.png'),
  cinema: require('./cinema_placeholder.jpg'),
  google: require('./google.png'),
  noResult: require('./no_result.png'),
  conexionLost: require('./conexion_lost.png'),
  underConstruction: require('./under_construction.png'),
  pageOne: require('./page_one.png'),
  pageTwo: require('./page_two.webp'),
  pageThree: require('./page_three.webp'),
};
