import {BaseGenres} from '../../tv_shows/entities/TVShows';
import {Item} from '../../base/Item';

// Generated by https://quicktype.io
export interface Movies {
  dates?: Dates;
  page: number;
  results: Movie[];
  totalPages: number;
  totalResults: number;
}

export interface Dates {
  maximum: string;
  minimum: string;
}

export interface Movie extends Item {
  adult: boolean;
  backdropPath: string;
  genreIds: BaseGenres[];
  id: number;
  originalTitle: string;
  overview: string;
  popularity: number;
  posterPath: string;
  releaseDate: string;
  title: string;
  video: boolean;
  voteAverage: number;
  voteCount: number;
  credits?: Credits;
  director?: string;
  trailer?: string;
  reviews?: Reviews;
}

export interface Credits {
  cast: Cast[];
  crew: Cast[];
}

export interface Cast {
  id: number;
  knownForDepartment: string;
  name: string;
  originalName: string;
  profilePath: null | string;
}

export interface Reviews {
  results: Review[];
}

export interface Review {
  author: string;
  authorDetails: AuthorDetails;
  content: string;
  createdAt: string;
  id: string;
  updatedAt: string;
  url: string;
}

export interface AuthorDetails {
  name: string;
  username: string;
  avatarPath: string;
  rating: number;
}
