// Generated by https://quicktype.io
export interface Movies {
    dates?: Dates;
    page: number;
    results: Movie[];
    totalPages: number;
    totalResults: number;
}

export interface Dates {
    maximum: string;
    minimum: string;
}

export interface Movie {
    adult: boolean;
    backdropPath: string;
    genreIds: number[];
    id: number;
    originalLanguage: OriginalLanguage;
    originalTitle: string;
    overview: string;
    popularity: number;
    posterPath: string;
    releaseDate: string;
    title: string;
    video: boolean;
    voteAverage: number;
    voteCount: number;
}

export enum OriginalLanguage {
    De = "de",
    En = "en",
    Es = "es",
}


